name: Sync with Master

on:
  schedule:
    - cron: '0 0 * * *'  # Cada dia a medianoche
  workflow_dispatch:      # Manual

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote src/core

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff --staged --quiet || git commit -m "chore: sync with Master"
          git push
